export const dadJokes: string[] = [
	"why don't skeletons fight each other? they don't have the guts.",
	"I used to be a banker, but I lost interest.",
	"why did the scarecrow win an award? he was outstanding in his field.",
	"I'm reading a book about anti-gravity, it's impossible to put down.",
	"why don't eggs tell jokes? they'd crack each other up.",
	"I only know 25 letters of the alphabet, I don't know y.",
	"what do you call a fish with no eyes? a fsh.",
	"why did the bicycle fall over? it was two tired.",
	"I used to hate facial hair, but then it grew on me.",
	"what do you call fake spaghetti? an impasta.",
	"why can't you give Elsa a balloon? she'll let it go.",
	"I'm on a seafood diet, I see food and I eat it.",
	"why did the golfer bring two pairs of pants? in case he got a hole in one.",
	"what do you call a bear with no teeth? a gummy bear.",
	"why did the math book look sad? it had too many problems.",
	"how do you organize a space party? you planet.",
	"why did the coffee file a police report? it got mugged.",
	"what do you call a can opener that doesn't work? a can't opener.",
	"why don't scientists trust atoms? because they make up everything.",
	"I told my wife she was drawing her eyebrows too high, she looked surprised.",
	"why did the tomato turn red? because it saw the salad dressing.",
	"what did the ocean say to the beach? nothing, it just waved.",
	"why did the cookie go to the doctor? because it felt crummy.",
	"how does a penguin build its house? igloos it together.",
	"why did the invisible man turn down the job offer? he couldn't see himself doing it.",
	"what do you call a dinosaur that crashes his car? tyrannosaurus wrecks.",
	"why don't oysters share? because they're shellfish.",
	"what's orange and sounds like a parrot? a carrot.",
	"why did the picture go to jail? because it was framed.",
	"what do you call a sleeping bull? a bulldozer.",
	"why did the stadium get hot after the game? all the fans left.",
	"how do you make a tissue dance? you put a little boogie in it.",
	"why did the belt get arrested? for holding up a pair of pants.",
	"what do you call a fish wearing a bowtie? sofishticated.",
	"why did the computer go to the doctor? it had a virus.",
	"what do you call a boomerang that doesn't come back? a stick.",
	"why did the chicken join a band? because it had the drumsticks.",
	"what did one wall say to the other wall? I'll meet you at the corner.",
	"why did the gym close down? it just didn't work out.",
	"what do you call cheese that isn't yours? nacho cheese.",
	"why did the barber win the race? he knew a shortcut.",
	"what's a skeleton's least favorite room in the house? the living room.",
	"why did the student eat his homework? the teacher told him it was a piece of cake.",
	"how do trees get on the internet? they log in.",
	"why did the developer go broke? he used up all his cache.",
	"what did the janitor say when he jumped out of the closet? supplies.",
	"why do bees have sticky hair? because they use honeycombs.",
	"what do you call a pig that does karate? a pork chop.",
	"why did the smartphone need glasses? it lost its contacts.",
	"what do you call a factory that makes okay products? a satisfactory.",
	"why did the pony get sent to its room? it wouldn't stop horsing around.",
	"what do you call a lazy kangaroo? a pouch potato.",
	"why don't melons get married? because they cantaloupe.",
	"what's the best time to go to the dentist? tooth hurty.",
	"why did the scientist install a knocker on his door? he wanted to win the no-bell prize.",
	"what do you call an alligator in a vest? an investigator.",
	"why did the man put his money in the freezer? he wanted cold hard cash.",
	"what do you call a snowman with a six-pack? an abdominal snowman.",
	"why did the teddy bear say no to dessert? because it was already stuffed.",
	"what did the buffalo say when his son left for college? bison.",
	"why did the crab never share? because he's shellfish.",
	"what do you call a very small valentine? a valen-tiny.",
	"why did the traffic light turn red? you'd turn red too if you had to change in the middle of the street.",
	"what do you call a group of disorganized cats? a cat-astrophe.",
	"why did the roof go to the doctor? it had shingles.",
	"what do you call a dog magician? a labracadabrador.",
	"why did the astronaut break up with his girlfriend? he needed space.",
	"what do you get when you cross a snowman and a vampire? frostbite.",
	"why did the man run around his bed? he was trying to catch up on his sleep.",
	"what do you call a fish that needs help with vocals? auto-tuna.",
	"why did the baker stop making donuts? he was tired of the hole business.",
	"what do you call a cow with no legs? ground beef.",
	"why did the light bulb fail the test? it wasn't that bright.",
	"what did the fisherman say to the magician? pick a cod, any cod.",
	"why don't seagulls fly over the bay? because then they'd be bagels.",
	"what do you call a dog that does magic tricks? a labracadabrador, again, it never gets old.",
	"why did the football coach go to the bank? to get his quarterback.",
	"what do you call a nervous javelin thrower? shakespeare.",
	"why did the mushroom get invited to every party? because he's a fungi.",
	"what do you call two birds in love? tweethearts.",
	"why did the calendar feel stressed? too many dates.",
	"what do you call a boring dinosaur? a thesaurus.",
	"why did the man bring a ladder to the bar? because he heard the drinks were on the house.",
	"what do you call an old snowman? water.",
	"why did the orange stop rolling? it ran out of juice.",
	"what do you call a fish without an eye? fsh, still true the second time.",
	"why did the volcano break up with the earthquake? it said the relationship was too shaky.",
	"what do you call a duck that gets straight A's? a wise quacker.",
	"why did the cell phone need glasses? it lost all its contacts, twice.",
	"what do you call an elephant that doesn't matter? irrelephant.",
	"why did the potato win the race? because it was a couch potato taking a shortcut.",
	"what do you call a bee that can't make up its mind? a maybe.",
	"why did the man go on a diet? he saw himself in the mirror horizontally.",
	"what do you call a pile of cats? a meow-ntain.",
	"why did the ghost go to the party? for the boos.",
	"what do you call a sad cup of coffee? a depresso.",
	"why did the leaf go to the doctor? it was feeling green.",
	"what do you call an owl who does magic? hoo-dini.",
	"why did the cookie cry? because its mom was a wafer so long.",
	"what do you call a fish that plays the piano? a piano tuna.",
	"deployed on a friday, said a little prayer, went home anyway.",
	"i got fired from the transmission factor, turns out i didn't put on enough shifts...",
	"where do young cows eat lunch? in the calf-ateria.",
	"i went to the doctor today and he told me i had type a blood but it was a type o.",
	"how does a french skeleton say hello? bone-jour.",
	"why was the big cat disqualified from the race? because it was a cheetah.",
	"what do prisoners use to call each other? cell phones.",
	"what’s e.t. short for? he’s only got little legs.",
	"we all know where the big apple is but does anyone know where the minneapolis?",
	"what do you call a monkey in a mine field? a babooooom!",
	"scientists finally did a study on forks. it's about tine!",
	"i cut my finger cutting cheese. i know it may be a cheesy story but i feel grate now.",
	"how do you steal a coat? you jacket.",
	"why don't you find hippopotamuses hiding in trees? they're really good at it.",
	"what happens when you cross a sheep with a kangaroo ? a woolly jumper!",
	"i’m reading a book on the history of glue – can’t put it down.",
	"want to hear a joke about construction? nah, i'm still working on it.",
	"why are fish easy to weigh? because they have their own scales.",
	"what did the scarf say to the hat? you go on ahead, i am going to hang around a bit longer.",
	"did you hear about the scientist who was lab partners with a pot of boiling water? he had a very esteemed colleague.",
	"this morning i was wondering where the sun was, but then it dawned on me.",
	"writing with a broken pencil is pointless.",
	'what did the sea say to the sand? "we have to stop meeting like this."',
	"why is it so windy inside an arena? all those fans.",
	"a panda walks into a bar and says to the bartender “i’ll have a scotch and . . . . . . . . . . . . . . coke thank you”. “sure thing” the bartender replies and asks “but what’s with the big pause?” the panda holds up his hands and says “i was born with them”",
	"what musical instrument is found in the bathroom? a tuba toothpaste.",
	"i can't take my dog to the pond anymore because the ducks keep attacking him. that's what i get for buying a pure bread dog.",
	"my boss told me to attach two pieces of wood together... i totally nailed it!",
	"what was the pumpkin’s favorite sport? squash.",
	"recent survey revealed 6 out of 7 dwarf's aren't happy.",
	"what do you call corn that joins the army? kernel.",
	"i've been trying to come up with a dad joke about momentum . . . but i just can't seem to get it going.",
	"‘put the cat out’ … ‘i didn’t realize it was on fire",
	"what do you get when you cross a snowman with a vampire? frostbite.",
	"what do you do when your bunny gets wet? you get your hare dryer.",
	"did you know crocodiles could grow up to 15 feet? but most just have 4.",
	"there are two types of people in this world, those who can extrapolate from incomplete data...",
	"why did the fireman wear red, white, and blue suspenders? to hold his pants up.",
	"in the news a courtroom artist was arrested today, i'm not surprised, he always seemed sketchy.",
	"i wanted to be a tailor but i didn't suit the job",
	"what do you call someone with no nose? nobody knows.",
	"i'm tired of following my dreams. i'm just going to ask them where they are going and meet up with them later.",
	"did you hear about the guy whose whole left side was cut off? he's all right now.",
	"why didn’t the skeleton cross the road? because he had no guts.",
	"what did one nut say as he chased another nut? i'm a cashew!",
	"where do fish keep their money? in the riverbank",
	"i accidentally took my cats meds last night. don’t ask meow.",
	"chances are if you' ve seen one shopping center, you've seen a mall.",
	"dermatologists are always in a hurry. they spend all day making rash decisions.",
	"what lies at the bottom of the ocean and twitches? a nervous wreck.",
	"what is red and smells like blue paint? red paint!",
	'*reversing the car* "ah, this takes me back"',
	"doctor you've got to help me, i'm addicted to twitter. doctor: i don't follow you.",
	"how do locomotives know where they're going? lots of training",
	"how did the hipster burn the roof of his mouth? he ate the pizza before it was cool.",
	"a butcher accidentally backed into his meat grinder and got a little behind in his work that day.",
	"did you hear about the new restaurant on the moon? the food is great, but there’s just no atmosphere.",
	"why was santa's little helper feeling depressed? because he has low elf esteem.",
	"why did sweden start painting barcodes on the sides of their battleships? so they could scandinavian.",
	"want to hear a chimney joke? got stacks of em! first one's on the house",
	"what do you call a pig that knows karate? a pork chop!",
	"if two vegans are having an argument, is it still considered beef?",
	"my sea sickness comes in waves.",
	"for valentine's day, i decided to get my wife some beads for an abacus. it's the little things that count.",
	"what's the worst thing about ancient history class? the teachers tend to babylon.",
	"some people say that i never got over my obsession with phil collins. but take a look at me now.",
	"why did the girl smear peanut butter on the road? to go with the traffic jam.",
	"it takes guts to be an organ donor.",
	"the rotation of earth really makes my day.",
	"how much does a hipster weigh? an instagram.",
	"a woman is on trial for beating her husband to death with his guitar collection. judge says, ‘first offender?’ she says, ‘no, first a gibson! then a fender!’",
	'i saw an ad in a shop window, "television for sale, $1, volume stuck on full", i thought, "i can\'t turn that down".',
	"what kind of dog lives in a particle accelerator? a fermilabrador retriever.",
];
