export const programmerJokes: string[] = [
	"why do programmers prefer dark mode? light attracts bugs.",
	"there are 10 types of people: those who understand binary and those who don't.",
	"it's not a bug, it's an undocumented feature.",
	"99 little bugs in the code, take one down, patch it around, 127 little bugs in the code.",
	"a SQL query walks into a bar, walks up to two tables and asks: can I join you?",
	"why do Java developers wear glasses? because they don't C#.",
	"in order to understand recursion, you must first understand recursion.",
	"I would tell you a UDP joke, but you might not get it.",
	"programming is 10% writing code and 90% figuring out why it doesn't work.",
	"real programmers count from 0.",
	"there's no place like 127.0.0.1.",
	"debugging: being the detective in a crime movie where you're also the murderer.",
	"software and cathedrals are much the same: first we build them, then we pray.",
	"a programmer is a machine that turns coffee into code.",
	"why do programmers hate nature? too many bugs, not enough documentation.",
	"a good programmer always looks both ways before crossing a one-way street.",
	"weeks of coding can save you hours of planning.",
	"works on my machine.",
	"it compiled? ship it.",
	"trust me, I'm a developer.",
	"one does not simply merge into main without conflicts.",
	"git commit -m 'fixed it for real this time'",
	"talk is cheap, show me the code.",
	"programmers never die, they just go into an infinite loop.",
	"there is no cloud, it's just someone else's computer.",
	"give a man a program, frustrate him for a day. teach a man to program, frustrate him for a lifetime.",
	"the best thing about a boolean is even if you're wrong, you're only off by a bit.",
	"how many programmers does it take to change a light bulb? none, that's a hardware problem.",
	"my code doesn't work, I have no idea why. my code works, I have no idea why.",
	"I'm not lazy, I'm just very committed to efficiency, someday.",
	"8 bytes walk into a bar, one says: I feel a bit off.",
	"the generation of random numbers is too important to be left to chance.",
	"Chuck Norris can compile syntax errors.",
	"there's a fine line between a bug and a feature.",
	"optimism is an occupational hazard of programming, feedback is the treatment.",
	"the best error message is the one that never shows up.",
	"coding: turning coffee into 'why is this not working'.",
	"programmer's diet: coffee, code, repeat.",
	"I don't always test my code, but when I do, I do it in production.",
	"real developers don't comment their code, if it was hard to write, it should be hard to read.",
	"my favorite HTTP status is 418: I'm a teapot.",
	"some people, when confronted with a problem, think 'I'll use regex'. now they have two problems.",
	"a byte walked into a bar looking rather drained.",
	"there are only two hard problems in computer science: cache invalidation and naming things.",
	"documentation is like sex, when it's good it's very good, and when it's bad it's better than nothing.",
	"the code was working yesterday.",
	"semicolons: the silent killer of code.",
	"rebooting fixes everything, until it doesn't.",
	"ctrl+z is my favorite feature in life.",
	"the three virtues of a programmer: laziness, impatience, and hubris.",
	"it's always DNS.",
	"AI won't replace programmers, it'll just add more bugs faster.",
	"machine learning: teaching a computer to guess better than you.",
	"I trained a neural network to write jokes, this is the best it could do.",
	"my code works in theory, and theory is close enough for a demo.",
	"the cake is a lie, but so is my estimate.",
	"there's an art to programming, it's called copy-pasting from Stack Overflow correctly.",
	"I don't need a debugger, I just insert print statements everywhere.",
	"console.log('why') // still figuring that out",
	"reality is often disappointing, unlike my code coverage report.",
	"npm install happiness — module not found.",
	"programmers dream in syntax errors.",
	"I speak fluent JavaScript and broken English, in that order.",
	"my relationship status: it's complicated, just like my code.",
	"404: motivation not found.",
	"I don't always write clean code, but when I do, no one believes it's mine.",
	"sleep is just a cache I haven't cleared yet.",
	"I turned off notifications, now I only have merge conflicts to worry about.",
	"a wild bug appeared, I used documentation, it's not very effective.",
	"my code is like my sense of humor, works about half the time.",
	"behind every great app is a developer who cried at least once debugging it.",
	"I don't have bugs, I have random features.",
	"warning: contains traces of spaghetti code.",
	"life hack: turn it off and on again.",
	"I asked an AI to fix my bug, now I have two bugs and an existential crisis.",
	"there are two types of code: the code that works, and the code nobody dares to touch.",
	"my code and my sleep schedule have the same bug: neither makes sense.",
	"powered by coffee and stubbornness.",
	"I don't fear bugs, bugs fear my deadline.",
	"currently debugging life, please hold.",
	"not all heroes wear capes, some just write good commit messages.",
	"I speak two languages: English and error messages.",
	"my code compiles, therefore I am, probably fine.",
	"behind every 'quick fix' is a story nobody wants to hear.",
	"I don't always test in production, but when I do, I don't tell anyone.",
	"currently arguing with a semicolon and losing.",
	"my GitHub contributions graph and my sleep schedule are both a mess.",
	"I turn 'it should work' into 'it works' one bug at a time.",
	"still trying to center a div, send help.",
	"powered by Stack Overflow and blind confidence.",
	"there's no place for perfectionists in a codebase this old.",
	"my two modes: it works and I don't know why, and it's broken and I don't know why.",
	"I don't always name my variables well, but when I don't, future me suffers.",
	"my code has more TODOs than actual done.",
	"friendship ended with jQuery, now React is my best friend.",
	"my keyboard's most used key is backspace.",
	"I write code like I write essays, mostly last minute.",
	"if it works, don't touch it, if it breaks, blame the last commit.",
	"my brain has two tabs open, and one of them is frozen.",
	"I don't need luck, I need better error messages.",
	"error 200: everything's fine, somehow.",
	"deployed on a Friday, prayed all weekend.",
	"udp is better in the covid era since it avoids unnecessary handshakes.",
	"// this line doesn't actually do anything, but the code stops working when i delete it.",
	'today i learned that changing random stuff until your program works is "hacky" and a "bad coding practice" but if you do it fast enough it\'s "machine learning" and pays 4x your current salary.',
	"a programmer puts two glasses on his bedside table before going to sleep. a full one, in case he gets thirsty, and an empty one, in case he doesn't.",
	'"knock, knock." "who\'s there?" [very long pause] "java."',
	"debugging is like being the detective in a crime movie where you're also the murderer at the same time.",
	'a sql statement walks into a bar and sees two tables. it approaches, and asks "may i join you?"',
	'two sql tables sit at the bar. a query approaches and asks "can i join you?"',
	"i've got a really good udp joke to tell you but i don’t know if you'll get it.",
	'a byte walks into a bar looking miserable. the bartender asks it: "what\'s wrong buddy?" "parity error." it replies. "ah that makes sense, i thought you looked a bit off."',
	"java and c were telling jokes. it was c's turn, so he writes something on the wall, points to it and says \"do you get the reference?\" but java didn't.",
	'a guy walks into a bar and asks for 1.4 root beers. the bartender says "i\'ll have to charge you extra, that\'s a root beer float". the guy says "in that case, better make it a double."',
	'eight bytes walk into a bar. the bartender asks, "can i get you anything?" "yeah," reply the bytes. "make us a double."',
	"the six stages of debugging: 1. that can't happen. 2. that doesn't happen on my machine. 3. that shouldn't happen. 4. why does that happen? 5. oh, i see. 6. how did that ever work?",
	"debugging: removing the needles from the haystack.",
];
