import type { Metadata } from "next";
import { DM_Sans, Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/layouts/navbar";
import { SiteFooter } from "@/components/layouts/site-footer";
import { SmoothScroll } from "@/components/layouts/smooth-scroll";
import { cn } from "@/lib/utils";

const dmSansHeading = DM_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        roboto.variable,
        dmSansHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {/* Global: smooth-scroll behavior, nav, and footer wrap every route. */}
        <SmoothScroll />
        <NavBar />
        {children}
        <SiteFooter />
      </body>
    </html>
  );
}
